spring:
  application:
    name: digital-parking-management
  datasource:
    url: jdbc:postgresql://localhost:5432/parking_db
    username: parking
    password: parking
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

app:
  jwt:
    secret: ZGlnaXRhbC1wYXJraW5nLW1hbmFnZW1lbnQtand0LXNlY3JldC1rZXktZG9ydG11bmQtMjAyNg==
    expiration-ms: 86400000
